model:
  dropout: 0.1
  freeze_encoder: false
  freeze_feature_encoder: true
  keep_layers: null
  layerdrop: 0.0
  mask_time_prob: 0.05
  pretrained_model: facebook/wav2vec2-base
  type: wav2vec2
  use_joint_head: false
training:
  batch_size: 16
  encoder_learning_rate: 3.0e-05
  epochs: 6
  fp16: true
  learning_rate: 0.001
